name: Run tests

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Run unittest
        run: |
          python -m unittest test_main_unit.py

  pytest:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip and pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run pytest
        run: |
          pytest test_main_pytest.py -v
